### ISSUE TITLE
Moodle.org plugins db title and pluginname confusing with original version of the plugin.

### ISSUE THREAD

**Issue by danmarsden** [CLAMP-IT/moodle-block_clampmail#64]
As this is a fork of an existing plugin which is still maintained in the plugins db, we really need to redefine the name of this one before we can approve it in the plugins db IMO.

I see you've called the repo and frankenstyle plugin name "clampmail" instead of "quickmail" - but all the lang strings (and in particular the pluginname) are the same. This is likely to cause confusion in the plugins db and community - can you please rename your pluginname to something other than "quickmail" - and make it "clampmail" or some other name to distinguish it from the other plugin within the plugins db?

personally I think this is an approval blocker.

**Comment by mackensen** [comment]
That's a reasonable suggestion.
