### ISSUE TITLE
readme should include better reference to original plugin

### ISSUE THREAD

**Issue by danmarsden** [CLAMP-IT/moodle-block_clampmail#66]
The readme file should be updated to clearly reference the original authors of  this plugin and preferably also include a link to their github repository.

this is a blocker for plugins db approval.

**Comment by mackensen** [comment]
@danmarsden I've updated the readme (see [0c645bf](https://github.com/CLAMP-IT/moodle-block_clampmail/commit/0c645bf6ea206fbdc1d9de64b28e26c1e59d8b7a)) to explicitly acknowledge the original institutional home and authors. Is that sufficient?

**Comment by danmarsden** [comment]
yeah that's what I was looking for - thanks! :-)
