### ISSUE TITLE
Behat tests fail on Moodle 4.2; pass manually

### ISSUE THREAD

**Issue by mackensen** [CLAMP-IT/moodle-block_clampmail#69]
See https://github.com/CLAMP-IT/moodle-block_clampmail/actions/runs/5785953195/job/15679648800. Full failure:

> 003 Scenario: Add and remove signatures # /home/runner/work/moodle-block_clampmail/moodle-block_clampmail/moodle/blocks/clampmail/tests/behat/signature.feature:23
>       Then I should see "Doom At 11"    # /home/runner/work/moodle-block_clampmail/moodle-block_clampmail/moodle/blocks/clampmail/tests/behat/signature.feature:46
>         "Doom At 11" text was found but was not visible
>         
>         +--[ http://localhost:8000/blocks/clampmail/signature.php?courseid=101000&id=457000 | WebDriver ]
>         |
>         |  <html dir="ltr" lang="en" xml:lang="en" class="yui3-js-enabled"><head>
>         |      <title>CLAMPMail: Manage signatures</title>
>         |      <link rel="shortcut icon" href="http://localhost:8000/theme/image.php/boost/theme/1691416287/favicon">
>         |      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
>         |  <meta name="keywords" content="moodle, CLAMPMail: Manage signatures">
>         |  <link rel="stylesheet" type="text/css" href="http://localhost:8000/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple.css"><script charset="utf-8" id="yui_3_18_1_1_1691416919605_8" src="http://localhost:8000/theme/yui_combo.php?m/1691416287/core/event/event-debug.js&amp;m/1691416287/filter_mathjaxloader/loader/loader-debug.js" async=""></script><script charset="utf-8" id="yui_3_18_1_1_1691416919605_19" src="https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js?delayStartupUntil=configured" async=""></script><script charset="utf-8" id="yui_3_18_1_1_1691416919605_20" src="http://localhost:8000/theme/yui_combo.php?3.18.1/eve...
>         |

The menu element is visible and usable in manual testing.

**Comment by mackensen** [comment]
@danmarsden have you seen this by any chance?

**Comment by mackensen** [comment]
Never mind, I just need to handle locator fields differently.

**Comment by danmarsden** [comment]
We don't tend to run unit/behat tests during the review process and I haven't been able to do a complete review yet, but hoping to find some time soon.
